package com.cjq.yicaijiaoyu.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.cjq.yicaijiaoyu.dao.Ad;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table AD.
*/
public class AdDao extends AbstractDao<Ad, Long> {

    public static final String TABLENAME = "AD";

    /**
     * Properties of entity Ad.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Ad_id = new Property(1, String.class, "ad_id", false, "AD_ID");
        public final static Property Ad_name = new Property(2, String.class, "ad_name", false, "AD_NAME");
        public final static Property Ad_link = new Property(3, String.class, "ad_link", false, "AD_LINK");
        public final static Property Image = new Property(4, String.class, "image", false, "IMAGE");
        public final static Property UserId = new Property(5, String.class, "userId", false, "USER_ID");
    };

    private DaoSession daoSession;


    public AdDao(DaoConfig config) {
        super(config);
    }
    
    public AdDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'AD' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'AD_ID' TEXT," + // 1: ad_id
                "'AD_NAME' TEXT," + // 2: ad_name
                "'AD_LINK' TEXT," + // 3: ad_link
                "'IMAGE' TEXT," + // 4: image
                "'USER_ID' TEXT);"); // 5: userId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'AD'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Ad entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String ad_id = entity.getAd_id();
        if (ad_id != null) {
            stmt.bindString(2, ad_id);
        }
 
        String ad_name = entity.getAd_name();
        if (ad_name != null) {
            stmt.bindString(3, ad_name);
        }
 
        String ad_link = entity.getAd_link();
        if (ad_link != null) {
            stmt.bindString(4, ad_link);
        }
 
        String image = entity.getImage();
        if (image != null) {
            stmt.bindString(5, image);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(6, userId);
        }
    }

    @Override
    protected void attachEntity(Ad entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Ad readEntity(Cursor cursor, int offset) {
        Ad entity = new Ad( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // ad_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // ad_name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // ad_link
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // image
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // userId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Ad entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAd_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAd_name(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAd_link(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setImage(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUserId(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Ad entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Ad entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
