package com.cjq.yicaijiaoyu.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.cjq.yicaijiaoyu.dao.CourseDao;
import com.cjq.yicaijiaoyu.dao.HistoryDao;
import com.cjq.yicaijiaoyu.dao.BoughtDao;
import com.cjq.yicaijiaoyu.dao.CaredDao;
import com.cjq.yicaijiaoyu.dao.ChapterDao;
import com.cjq.yicaijiaoyu.dao.VideoDao;
import com.cjq.yicaijiaoyu.dao.CommentsDao;
import com.cjq.yicaijiaoyu.dao.CategoryDao;
import com.cjq.yicaijiaoyu.dao.LectureDao;
import com.cjq.yicaijiaoyu.dao.AdDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        CourseDao.createTable(db, ifNotExists);
        HistoryDao.createTable(db, ifNotExists);
        BoughtDao.createTable(db, ifNotExists);
        CaredDao.createTable(db, ifNotExists);
        ChapterDao.createTable(db, ifNotExists);
        VideoDao.createTable(db, ifNotExists);
        CommentsDao.createTable(db, ifNotExists);
        CategoryDao.createTable(db, ifNotExists);
        LectureDao.createTable(db, ifNotExists);
        AdDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        CourseDao.dropTable(db, ifExists);
        HistoryDao.dropTable(db, ifExists);
        BoughtDao.dropTable(db, ifExists);
        CaredDao.dropTable(db, ifExists);
        ChapterDao.dropTable(db, ifExists);
        VideoDao.dropTable(db, ifExists);
        CommentsDao.dropTable(db, ifExists);
        CategoryDao.dropTable(db, ifExists);
        LectureDao.dropTable(db, ifExists);
        AdDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(CourseDao.class);
        registerDaoClass(HistoryDao.class);
        registerDaoClass(BoughtDao.class);
        registerDaoClass(CaredDao.class);
        registerDaoClass(ChapterDao.class);
        registerDaoClass(VideoDao.class);
        registerDaoClass(CommentsDao.class);
        registerDaoClass(CategoryDao.class);
        registerDaoClass(LectureDao.class);
        registerDaoClass(AdDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
