package com.cjq.yicaijiaoyu.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.cjq.yicaijiaoyu.dao.Course;
import com.cjq.yicaijiaoyu.dao.Video;

import com.cjq.yicaijiaoyu.dao.CourseDao;
import com.cjq.yicaijiaoyu.dao.VideoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig courseDaoConfig;
    private final DaoConfig videoDaoConfig;

    private final CourseDao courseDao;
    private final VideoDao videoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        courseDaoConfig = daoConfigMap.get(CourseDao.class).clone();
        courseDaoConfig.initIdentityScope(type);

        videoDaoConfig = daoConfigMap.get(VideoDao.class).clone();
        videoDaoConfig.initIdentityScope(type);

        courseDao = new CourseDao(courseDaoConfig, this);
        videoDao = new VideoDao(videoDaoConfig, this);

        registerDao(Course.class, courseDao);
        registerDao(Video.class, videoDao);
    }
    
    public void clear() {
        courseDaoConfig.getIdentityScope().clear();
        videoDaoConfig.getIdentityScope().clear();
    }

    public CourseDao getCourseDao() {
        return courseDao;
    }

    public VideoDao getVideoDao() {
        return videoDao;
    }

}
