package com.cjq.yicaijiaoyu.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.cjq.yicaijiaoyu.dao.Course;
import com.cjq.yicaijiaoyu.dao.History;
import com.cjq.yicaijiaoyu.dao.Bought;
import com.cjq.yicaijiaoyu.dao.Cared;
import com.cjq.yicaijiaoyu.dao.Chapter;
import com.cjq.yicaijiaoyu.dao.Video;
import com.cjq.yicaijiaoyu.dao.Comments;
import com.cjq.yicaijiaoyu.dao.Category;
import com.cjq.yicaijiaoyu.dao.Lecture;
import com.cjq.yicaijiaoyu.dao.Ad;

import com.cjq.yicaijiaoyu.dao.CourseDao;
import com.cjq.yicaijiaoyu.dao.HistoryDao;
import com.cjq.yicaijiaoyu.dao.BoughtDao;
import com.cjq.yicaijiaoyu.dao.CaredDao;
import com.cjq.yicaijiaoyu.dao.ChapterDao;
import com.cjq.yicaijiaoyu.dao.VideoDao;
import com.cjq.yicaijiaoyu.dao.CommentsDao;
import com.cjq.yicaijiaoyu.dao.CategoryDao;
import com.cjq.yicaijiaoyu.dao.LectureDao;
import com.cjq.yicaijiaoyu.dao.AdDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig courseDaoConfig;
    private final DaoConfig historyDaoConfig;
    private final DaoConfig boughtDaoConfig;
    private final DaoConfig caredDaoConfig;
    private final DaoConfig chapterDaoConfig;
    private final DaoConfig videoDaoConfig;
    private final DaoConfig commentsDaoConfig;
    private final DaoConfig categoryDaoConfig;
    private final DaoConfig lectureDaoConfig;
    private final DaoConfig adDaoConfig;

    private final CourseDao courseDao;
    private final HistoryDao historyDao;
    private final BoughtDao boughtDao;
    private final CaredDao caredDao;
    private final ChapterDao chapterDao;
    private final VideoDao videoDao;
    private final CommentsDao commentsDao;
    private final CategoryDao categoryDao;
    private final LectureDao lectureDao;
    private final AdDao adDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        courseDaoConfig = daoConfigMap.get(CourseDao.class).clone();
        courseDaoConfig.initIdentityScope(type);

        historyDaoConfig = daoConfigMap.get(HistoryDao.class).clone();
        historyDaoConfig.initIdentityScope(type);

        boughtDaoConfig = daoConfigMap.get(BoughtDao.class).clone();
        boughtDaoConfig.initIdentityScope(type);

        caredDaoConfig = daoConfigMap.get(CaredDao.class).clone();
        caredDaoConfig.initIdentityScope(type);

        chapterDaoConfig = daoConfigMap.get(ChapterDao.class).clone();
        chapterDaoConfig.initIdentityScope(type);

        videoDaoConfig = daoConfigMap.get(VideoDao.class).clone();
        videoDaoConfig.initIdentityScope(type);

        commentsDaoConfig = daoConfigMap.get(CommentsDao.class).clone();
        commentsDaoConfig.initIdentityScope(type);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        lectureDaoConfig = daoConfigMap.get(LectureDao.class).clone();
        lectureDaoConfig.initIdentityScope(type);

        adDaoConfig = daoConfigMap.get(AdDao.class).clone();
        adDaoConfig.initIdentityScope(type);

        courseDao = new CourseDao(courseDaoConfig, this);
        historyDao = new HistoryDao(historyDaoConfig, this);
        boughtDao = new BoughtDao(boughtDaoConfig, this);
        caredDao = new CaredDao(caredDaoConfig, this);
        chapterDao = new ChapterDao(chapterDaoConfig, this);
        videoDao = new VideoDao(videoDaoConfig, this);
        commentsDao = new CommentsDao(commentsDaoConfig, this);
        categoryDao = new CategoryDao(categoryDaoConfig, this);
        lectureDao = new LectureDao(lectureDaoConfig, this);
        adDao = new AdDao(adDaoConfig, this);

        registerDao(Course.class, courseDao);
        registerDao(History.class, historyDao);
        registerDao(Bought.class, boughtDao);
        registerDao(Cared.class, caredDao);
        registerDao(Chapter.class, chapterDao);
        registerDao(Video.class, videoDao);
        registerDao(Comments.class, commentsDao);
        registerDao(Category.class, categoryDao);
        registerDao(Lecture.class, lectureDao);
        registerDao(Ad.class, adDao);
    }
    
    public void clear() {
        courseDaoConfig.getIdentityScope().clear();
        historyDaoConfig.getIdentityScope().clear();
        boughtDaoConfig.getIdentityScope().clear();
        caredDaoConfig.getIdentityScope().clear();
        chapterDaoConfig.getIdentityScope().clear();
        videoDaoConfig.getIdentityScope().clear();
        commentsDaoConfig.getIdentityScope().clear();
        categoryDaoConfig.getIdentityScope().clear();
        lectureDaoConfig.getIdentityScope().clear();
        adDaoConfig.getIdentityScope().clear();
    }

    public CourseDao getCourseDao() {
        return courseDao;
    }

    public HistoryDao getHistoryDao() {
        return historyDao;
    }

    public BoughtDao getBoughtDao() {
        return boughtDao;
    }

    public CaredDao getCaredDao() {
        return caredDao;
    }

    public ChapterDao getChapterDao() {
        return chapterDao;
    }

    public VideoDao getVideoDao() {
        return videoDao;
    }

    public CommentsDao getCommentsDao() {
        return commentsDao;
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public LectureDao getLectureDao() {
        return lectureDao;
    }

    public AdDao getAdDao() {
        return adDao;
    }

}
