package com.cjq.yicaijiaoyu.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.cjq.yicaijiaoyu.dao.History;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table HISTORY.
*/
public class HistoryDao extends AbstractDao<History, Long> {

    public static final String TABLENAME = "HISTORY";

    /**
     * Properties of entity History.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Authority = new Property(2, Integer.class, "authority", false, "AUTHORITY");
        public final static Property Image = new Property(3, String.class, "image", false, "IMAGE");
        public final static Property UserId = new Property(4, String.class, "userId", false, "USER_ID");
        public final static Property Order = new Property(5, Long.class, "order", false, "ORDER");
        public final static Property Cared = new Property(6, Boolean.class, "cared", false, "CARED");
        public final static Property Bought = new Property(7, Boolean.class, "bought", false, "BOUGHT");
        public final static Property CategoryName = new Property(8, String.class, "categoryName", false, "CATEGORY_NAME");
        public final static Property Goods_id = new Property(9, String.class, "goods_id", false, "GOODS_ID");
        public final static Property Info = new Property(10, String.class, "info", false, "INFO");
    };

    private DaoSession daoSession;


    public HistoryDao(DaoConfig config) {
        super(config);
    }
    
    public HistoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'HISTORY' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'NAME' TEXT," + // 1: name
                "'AUTHORITY' INTEGER," + // 2: authority
                "'IMAGE' TEXT," + // 3: image
                "'USER_ID' TEXT," + // 4: userId
                "'ORDER' INTEGER," + // 5: order
                "'CARED' INTEGER," + // 6: cared
                "'BOUGHT' INTEGER," + // 7: bought
                "'CATEGORY_NAME' TEXT," + // 8: categoryName
                "'GOODS_ID' TEXT," + // 9: goods_id
                "'INFO' TEXT);"); // 10: info
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'HISTORY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, History entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        Integer authority = entity.getAuthority();
        if (authority != null) {
            stmt.bindLong(3, authority);
        }
 
        String image = entity.getImage();
        if (image != null) {
            stmt.bindString(4, image);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(5, userId);
        }
 
        Long order = entity.getOrder();
        if (order != null) {
            stmt.bindLong(6, order);
        }
 
        Boolean cared = entity.getCared();
        if (cared != null) {
            stmt.bindLong(7, cared ? 1l: 0l);
        }
 
        Boolean bought = entity.getBought();
        if (bought != null) {
            stmt.bindLong(8, bought ? 1l: 0l);
        }
 
        String categoryName = entity.getCategoryName();
        if (categoryName != null) {
            stmt.bindString(9, categoryName);
        }
 
        String goods_id = entity.getGoods_id();
        if (goods_id != null) {
            stmt.bindString(10, goods_id);
        }
 
        String info = entity.getInfo();
        if (info != null) {
            stmt.bindString(11, info);
        }
    }

    @Override
    protected void attachEntity(History entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public History readEntity(Cursor cursor, int offset) {
        History entity = new History( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // authority
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // image
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // userId
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // order
            cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0, // cared
            cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0, // bought
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // categoryName
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // goods_id
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10) // info
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, History entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAuthority(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setImage(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setUserId(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setOrder(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setCared(cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0);
        entity.setBought(cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0);
        entity.setCategoryName(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setGoods_id(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setInfo(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(History entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(History entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
